language: node_js
node_js:
- '0.12'
branches:
  except:
  - gh-pages
env:
  global:
  - secure: Fd9k6cvvsk1z6SORWt7qHiqEcWaWN2Z6/L9ttvyXXNMX2HLH+oMFBe71g/ssL09jqRQta0YseApcvCDseZg6BM1U649gBMWGxSzKPpUlIJDgAXZ5so6lI2BPoWJbKhTKqo1cLRiMo2nm3aUau7pzlfwjByYxV8MYZxERcSt0OOCkz3bLvGr1HNvTC7/SuddJ7g9J/XHP+AxiBWA+gOOBR+qgUj5rfE6LnCca3p69oh8Os46W8rnUjfE0gAJHcxjDXx5+cYJME1f+VzZj7rT0XbabE5K6snJaIT7uv2Igl9zTecv/3613QcK/zL7+s+SPSFwKWmpNfD7PQkM/ACOI5CVos4clVhsYgbWkOYQ2MrMG4iYD4ZetVZAXyOkNGcKkhV44fwGOQl/sakNO7/ODoXhV5kPnSdB7T7/RU4JewDMawn8Q5TiGL3foyf9OvcQarzPaZk+7QFek2+ppzLTZ8vB7RkfSBCiqKiRe0t9lQvg+Laxluoy9qxb7cYDKpGnadI6bFuS3rNYOEhU8BhP1h5rBOAGwmvFjHLeMQNxBmdcPQ7HhRMC5gcfGEMEXjN3vvIp5wRspu8WfqaHuGITisBvPD5QpSV5YzWtxZSRzi+hnKBhRjK/6IWAq1hud1D7wVuiZyZjQ7a7+dMJ4fUWnVfhFv5CazsC86GM+B6FQkc4=
  - secure: 166jAvE3njnkxJmkeoZX0E+aen+jvkKJsH44WbXdipQfHu08WOeRirzU7Dw/WcP8lAsA+TfAOethgdG5zlEIkPGKR0CUEAS0qi/YHti6GXuBWLwmxUpg1xBDMg3wkx5w/19jyMPV9NlNU3MCYtYcLgR3SUaAsIz56WuoClBQebnOk8ZULod9sXExEKR0K9Hj8sNuHyX7Gei+6gdEDmRB5Vx2fqjVonEm5a3+RH6o6O8Khbo2FuxSmxvDSHRerDf2RWBgyxAhD7UXs9XKH7jLGdRG6sc7ZSiNBcM7fiBFf7LYV0ALNa2jCGa+PWlVWWN021hgRTBGXnWhL4EMBEJk+AiT8aJFUrFKfXa40gcwSUsl5yrRxXS0dXx3b/yTVgu29qx3cOebuHB/FYyTc2jL9fnXD2v2+J2g4VScp3q+b2Wr9WSO76TXRsWxjfLVXY56FUwGhzPTsqMUpaCka+L0AIXkeoJ3xLw+7kNdOQlaqQlrNneLoQpWLO5zA3WqhVlQ5RfF1NpDHw1GLqJ9gp+pWu3e5yxgQ6XIiqZXKFhW8o4Cckr7ggcjNnGtSHzHPbES5F4tJOYH6uoESc355RZ3gzh3po2LHAb+pO5CYqehhJMkYhBOQP6bZRIa2FclqpsjXTX6g4dipOt1pv4Ns8zNNVUqWPWGxUhA2niYBKUvaD8=
before_install:
- openssl aes-256-cbc -K $encrypted_3fc38785a9f9_key -iv $encrypted_3fc38785a9f9_iv
  -in ssh_deploy_key.enc -out ssh_deploy_key -d
after_success:
- chmod 600 ssh_deploy_key
- ssh-add ssh_deploy_key
- scripts/deploy.sh
